### ISSUE TITLE
Not running locally on Windows 10

### ISSUE THREAD

**Issue by Suleman-Elahi** [eashish93/imgsquash#3]
Front end after running is not able to compress images. I didn't check the API part as I don't have GCP account. After uploading status, it throws an error i don't know what's causing this.

![image](https://user-images.githubusercontent.com/24384996/58452958-d7c8f800-8136-11e9-8051-47e3a675d30a.png)

**Comment by eashish93** [comment]
frontend will not work without api service. It just a view. Also you need GCP account, a free account will works.
